VERSION 5.00
Begin VB.Form FrmEnqBed 
   Caption         =   "Bed Enquiry"
   ClientHeight    =   3195
   ClientLeft      =   3945
   ClientTop       =   3030
   ClientWidth     =   4680
   Icon            =   "FrmEnqBed.frx":0000
   LinkTopic       =   "Form1"
   ScaleHeight     =   3195
   ScaleWidth      =   4680
End
Attribute VB_Name = "FrmEnqBed"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
